### ISSUE TITLE
Accuracy.

### ISSUE THREAD

**Issue by rashmisgh** [vudung45/FaceRec#20]
Why is it not detecting the side faces? Accuracy is good only with the front faces.

**Comment by vudung45** [comment]
Side faces recognition accuracy depends on the image quality of ur side faces dataset ( left, or right).
You can certainly modify the source code I provided to further break the face into more regions like (up, down, up left, down left, etc); should be fairly easy if you read the code.

As for face detection, no open source face detection is perfect. I found mtcnn to be the best one I've tried so far that's why I implemented it for this repo. However, you might find opencv open source facial detection to be better at detecting side faces. I do warn you that there will be a lot of false positives with opencv face detection though. Again, mtcnn works best and smoothly for me with a GPU; that's why I chose it.

Hope this help

**Comment by mactiendinh** [comment]
Như trong demo, bạn show ra khung mặt + label tên + độ chính xác. Bạn cho mình hỏi độ chính xác đó được tính như nào ?? Thank kiu bạn

**Comment by rashmisgh** [comment]
@vudung45  whats the amount of side profile is required for detection? And how can I include up, down and up-left? I am talking only about detection, not recognition?

**Comment by vudung45** [comment]
I’ve explained ways that could improve detection above. MTCNN works best
for me, that’s why I used it. OpenCV object detection is also another good
alternetive. Play around with those and pick the one that works best for
you.
